
security:
  oauth2:
    client:
      clientId: myClient
      clientSecret: myClientSecret
      authorized-grant-types: authorization_code,refresh_token,password
      scope: openid
    resource.jwt:
      key-store: keystore.jks
      key-store-password: mystorepass
      key-alias: mytestkey

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    hikari:
      allow-pool-suspension: true
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    org:
      springframework: INFO
      hibernate.: DEBUG
server:
  port: 8080

web:
  cors:
    allowed-origins: "http://localhost:3000"
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    max-age: 3600
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"